version: '3'

services:
  postgres-db:
    image: postgres:15.3
    container_name: postgres-local
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  pg-admin:
    depends_on:
      - postgres-db
    image: dpage/pgadmin4:8.4
    container_name: pg-admin-local
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=code@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=123456